INSERT INTO GITHUB_PROJECT(ORG_NAME, REPO_NAME) VALUES ('sprint-projects', 'spring-boot');
INSERT INTO GITHUB_PROJECT(ORG_NAME, REPO_NAME) VALUES ('spring-io', 'initializr');
INSERT INTO GITHUB_PROJECT(ORG_NAME  , REPO_NAME) VALUES ('spring-io', 'xyz');